### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by DevBalek** [thomas545/ecommerce_api#132]
We have issue with project packages, lots of them have conflict and some packages removed from Pypi CLI sth. Please check out.

**Comment by davidemusi** [comment]
Hello Team, 

Can I still check on this issue?

**Comment by selvakumarbuzz** [comment]
Hi team I face  The user requested Django==2.1.11
    channels 2.3.0 depends on Django>=1.11
    django-allauth 0.39.1 depends on Django>=1.11
    django-crontab 0.7.1 depends on Django>=1.8
    django-debug-toolbar 2.0 depends on Django>=1.11
    django-filter 2.2.0 depends on Django>=1.11
    django-haystack 2.8.1 depends on Django>=1.11
    django-import-export 1.2.0 depends on django>=1.8
    django-jet 1.0.8 depends on Django
    django-mptt 0.10.0 depends on Django>=1.11
    django-phonenumber-field 3.0.1 depends on Django>=1.11.3
    django-redis 4.10.0 depends on Django>=1.11
    django-rest-auth 0.9.5 depends on Django>=1.8.0
    django-twilio 0.10.0 depends on Django<2.2 and >=1.11
    django-uuidfield 0.5.0 depends on django
    drf-haystack 1.8.7 depends on Django<3.1 and >=2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by thomas545** [comment]
Packages issue Fixed [PR #103 ](https://github.com/thomas545/ecommerce_api/pull/103)
